# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night:
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo research group theme powered by Wowchemy website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false  # Enable or disable code syntax highlighting
    extra_languages:
      - r          # Additional supported programming language: R
      - latex      # Additional supported programming language: LaTeX
  math:
    enable: false  # Enable or disable support for math formulas
  privacy_pack:
    enable: false  # Enable or disable privacy protection features
  repository:
    url: 'https://github.com/<username>/<repository>'  # GitHub repository URL
    content_dir: content  # Directory for content
    branch: main  # Branch to use
  avatar:
    gravatar: false  # Enable or disable Gravatar avatars
    shape: circle  # Shape of the avatar
  comment:
    provider: ''  # Comment system provider
    disqus:
      shortname: ''  # Disqus shortname
      show_count: true  # Show comment count
    commento:
      url: ''  # Commento URL
    giscus:
      repo: ''  # Giscus repository
      repo_id: ''  # Giscus repository ID
      category: ''  # Giscus category
      category_id: ''  # Giscus category ID
  search:
    provider: wowchemy  # Search provider
    algolia:
      app_id: ''  # Algolia application ID
      api_key: ''  # Algolia API key
      index_name: ''  # Algolia index name
      show_logo: false  # Show Algolia logo
  map:
    provider: 'mapnik'  # Map provider
    api_key: ''  # Map API key
    zoom: 15  # Map zoom level

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
